---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: og-scoped
  namespace: og-scoped
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oc-scoped
  namespace: labs-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: og-scoped
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: labs-ci-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oc-scoped
  namespace: labs-test
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: og-scoped
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: labs-ci-cd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oc-scoped
  namespace: labs-staging
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: og-scoped
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: labs-ci-cd
