apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: argocd-sync-and-wait
  labels:
    rht-labs.com/uj: ubiquitous-journey
spec:
  workspaces:
  - name: argocd-env-secret
  params:
  - name: application-name
    type: string
    description: name of the application to sync
  - name: revision
    type: string
    description: the revision to sync to
    default: master
  - name: flags
    type: string
    default: --
  - name: argocd-version
    type: string
    default: v1.8.6
  - name: argocd-server
    type: string
    default: argocd-server
  steps:
    - name: sync
      image: argoproj/argocd:$(params.argocd-version)
      script: |
        #set -ex
        argocd app wait $(params.application-name) --server $(params.argocd-server) --health $(params.flags) --timeout 120 --auth-token $(cat $(workspaces.argocd-env-secret.path)/password)
        if [ ! -z $(params.revision) ]; then
          argocd app sync $(params.application-name) --server $(params.argocd-server) --revision $(params.revision) $(params.flags) --timeout 600 --auth-token $(cat $(workspaces.argocd-env-secret.path)/password)
        else
          argocd app sync $(params.application-name) --server $(params.argocd-server) $(params.flags) --timeout 600 --auth-token $(cat $(workspaces.argocd-env-secret.path)/password)
        fi
        argocd app wait $(params.application-name) --server $(params.argocd-server) --health $(params.flags) --timeout 120 --auth-token $(cat $(workspaces.argocd-env-secret.path)/password)
