apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-source
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: openshift.org/aws-efs
  labels:
    rht-labs.com/uj: ubiquitous-journey
spec:
  resources:
    requests:
      storage: 2Gi
  storageClassName: aws-efs
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
