---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-webhook
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: build-tool
    tekton.dev/displayName: "create github webhook"
spec:
  workspaces:
    - name: git-auth-secret
  params:
    - name: ExternalDomain
      description: "The external domain for the EventListener e.g. `$(params.EventListenerName).<PROXYIP>.nip.io`"
    - name: GitHubUser
      description: "The GitHub user"
    - name: GitHubRepo
      description: "The GitHub repo where the webhook will be created"
    - name: GitHubOrg
      description: "The GitHub organization where the webhook will be created"
    - name: GitHubAccessTokenKey
      description: "The GitHub access token key name"
    - name: GitHubSecretStringKey
      description: "The GitHub secret string key name"
    - name: GitHubDomain
      description: "The GitHub domain. Override for GitHub Enterprise"
      default: "github.com"
    - name: WebhookEvents
      description: "List of events the webhook will send notifications for"
      default: '[\"push\",\"pull_request\"]'
  steps:
    - name: create-webhook
      image: quay.io/eformat/jenkins-agent-mvn-mandrel:latest
      command: ["/bin/bash", "-c"]
      args:
      - |
        set -e
        echo "Create Webhook"
        if [ $(params.GitHubDomain) = "github.com" ];then
          curl -v -d "{\"name\": \"web\",\"active\": true,\"events\": $(params.WebhookEvents),\"config\": {\"url\": \"$(params.ExternalDomain)\",\"content_type\": \"json\",\"insecure_ssl\": \"1\" ,\"secret\": \"$(cat $(workspaces.git-auth-secret.path)/$(params.GitHubSecretStringKey))\"}}" -X POST -u $(params.GitHubUser):$(cat $(workspaces.git-auth-secret.path)/$(params.GitHubAccessTokenKey)) -L https://api.github.com/repos/$(params.GitHubOrg)/$(params.GitHubRepo)/hooks
        else
          curl -d "{\"name\": \"web\",\"active\": true,\"events\": $(params.WebhookEvents),\"config\": {\"url\": \"$(params.ExternalDomain)/\",\"content_type\": \"json\",\"insecure_ssl\": \"1\" ,\"secret\": \"$(cat $(workspaces.git-auth-secret.path)/$(params.GitHubSecretStringKey))\"}}" -X POST -u $(params.GitHubUser):$(cat $(workspaces.git-auth-secret.path)/$(params.GitHubAccessTokenKey)) -L https://$(params.GitHubDomain)/api/v3/repos/$(params.GitHubOrg)/$(params.GitHubRepo)/hooks
        fi
