##############
# Application Custom Values
#############
stage_allowed_destinations: &stage_allowed_destinations
  - namespace: labs-staging
    server: https://kubernetes.default.svc
helm_repository: &helm_repo "http://sonatype-nexus-service.labs-ci-cd.svc.cluster.local:8081/repository/helm-charts/"
##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/triggers/0/imageChangeParams/lastTriggeredImage
        - /spec/triggers/1/imageChangeParams/lastTriggeredImage
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/containers/1/image
##############
# Argo App of Apps declaration
#############
argocd_projects:
  - enabled: true
    name: pet-battle-stage
    destinations: *stage_allowed_destinations
applications:
  pet_battle_api_stage:
    name: pet-battle-api-stage
    enabled: true
    source: *helm_repo
    chart_name: pet-battle-api
    sync_policy_automated: true
    destination: labs-staging
    source_ref: 1.0.13
    values:
      fullnameOverride: pet-battle-api
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-api
      image_version: "ec9c41a"
      istag:
        enabled: false
      deploymentConfig: false
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-stage
      enabled: true
  pet_battle_stage:
    name: pet-battle-stage
    enabled: true
    source: *helm_repo
    chart_name: pet-battle
    sync_policy_automated: true
    destination: labs-staging
    source_ref: 1.0.1
    values:
      fathom: true
      fullnameOverride: pet-battle
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle
      image_namespace: labs-staging
      config_map: '{ "catsUrl": "https://pet-battle-api-labs-staging.apps.hivec.sandbox380.opentlc.com", "tournamentsUrl": "https://pet-battle-tournament-labs-staging.apps.hivec.sandbox380.opentlc.com", "keycloak": { "url": "https://keycloak-labs-staging.apps.hivec.sandbox380.opentlc.com/auth/", "realm": "pbrealm", "clientId": "pbclient", "redirectUri": "https://pet-battle-labs-staging.apps.hivec.sandbox380.opentlc.com/*", "enableLogging": true } }'
      image_version: "de810dd"
    project:
      name: pet-battle-stage
      enabled: true
  pet_battle_tournament_stage:
    name: pet-battle-tournament-stage
    enabled: true
    source: *helm_repo
    chart_name: pet-battle-tournament
    sync_policy_automated: true
    destination: labs-staging
    source_ref: 1.0.32
    values:
      fullnameOverride: pet-battle-tournament
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-tournament
      image_namespace: labs-staging
      image_version: "master"
      istag:
        enabled: false
      pet-battle-infra:
        app_domain: apps.hivec.sandbox380.opentlc.com
        ignoreHelmHooks: true
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-stage
      enabled: true
  pb_analytics:
    name: fathom
    enabled: true
    source: https://github.com/petbattle/pet-battle-analytics.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-staging
    source_ref: master
