##############
# Application Custom Values
#############
pet_battle_api_values: &pet_battle_api_values
  fullnameOverride: pet-battle-api # important to use this if want same app name in multiple ns, else release.name used in chart
  image_repository: image-registry.openshift-image-registry.svc:5000
  image_name: pet-battle-api
dev_allowed_destinations: &dev_allowed_destinations # argocd project
  - namespace: labs-dev
    server: https://kubernetes.default.svc
test_allowed_destinations: &test_allowed_destinations # argocd project
  - namespace: labs-test
    server: https://kubernetes.default.svc

##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
  - group: apps.openshift.io
    kind: DeploymentConfig
    jsonPointers:
    - /spec/replicas
    - /spec/template/spec/containers/0/image
    - /spec/triggers/0/imageChangeParams/lastTriggeredImage
    - /spec/triggers/1/imageChangeParams/lastTriggeredImage

##############
# Argo App of Apps declaration
#############
argocd_projects:
- enabled: true
  name: pet-battle-dev
  destinations: *dev_allowed_destinations
- enabled: true
  name: pet-battle-test
  destinations: *test_allowed_destinations

applications:
  pet_battle_api_dev:
    name: pet-battle-api-dev
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/pet-battle-api.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master # overridden by git revision in pipeline trigger
    values: *pet_battle_api_values
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-dev
      enabled: true
  pet_battle_api_test:
    name: pet-battle-api-test
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/pet-battle-api.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-test
    source_ref: master # overridden by git revision in pipeline trigger
    values: *pet_battle_api_values
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-test
      enabled: true
  pet_battle_dev:
    name: pet-battle-dev
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/pet-battle.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master
    values:
      app_tag: master
      fullnameOverride: pet-battle
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle
      image_namespace: labs-dev
      config_map: "'http://pet-battle-api-labs-dev.apps.hivec.sandbox1862.opentlc.com'"
    project:
      name: pet-battle-dev
      enabled: true
  pet_battle_test:
    name: pet-battle-test
    enabled: false # overridden by pipeline
    source: https://github.com/eformat/pet-battle.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-test
    source_ref: master
    values:
      app_tag: master
      fullnameOverride: pet-battle
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle
      image_namespace: labs-test
      config_map: "'http://pet-battle-api-labs-test.apps.hivec.sandbox1862.opentlc.com'"
    project:
      name: pet-battle-test
      enabled: true
  pet_battle_tournament_dev:
    name: pet-battle-tournament-dev
    enabled: false # overridden by pipeline
    source: https://github.com/petbattle/tournamentservice-v1.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master
    values:
      app_tag: master
      fullnameOverride: pet-battle-tournament
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-tournament
      image_namespace: labs-dev
      config_map: "'http://pet-battle-api-labs-dev.apps.hivec.sandbox1862.opentlc.com'"
      operatorgroup:
        targetNamespaces: 
          - labs-dev
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-dev
      enabled: true
  pet_battle_tournament_test:
    name: pet-battle-tournament-test
    enabled: false # overridden by pipeline
    source: https://github.com/petbattle/tournamentservice-v1.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-test
    source_ref: master
    values:
      app_tag: master
      fullnameOverride: pet-battle-tournament
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle
      image_namespace: labs-test
      config_map: "'http://pet-battle-api-labs-test.apps.hivec.sandbox1862.opentlc.com'"
      operatorgroup:
        targetNamespaces: 
          - labs-test
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-test
      enabled: true

