##############
# Application Custom Values
#############
dev_allowed_destinations: &dev_allowed_destinations
  - namespace: labs-dev
    server: https://kubernetes.default.svc
test_allowed_destinations: &test_allowed_destinations
  - namespace: labs-test
    server: https://kubernetes.default.svc
helm_repository: &helm_repo "http://sonatype-nexus-service.labs-ci-cd.svc.cluster.local:8081/repository/helm-charts/"
##############
# Argo Ignore Differences
#############
ignore_differences: &ignore_differences
  ignoreDifferences:
    - group: apps.openshift.io
      kind: DeploymentConfig
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/triggers/0/imageChangeParams/lastTriggeredImage
        - /spec/triggers/1/imageChangeParams/lastTriggeredImage
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
        - /spec/template/spec/containers/0/image
        - /spec/template/spec/containers/1/image
##############
# Argo App of Apps declaration
#############
argocd_projects:
  - enabled: true
    name: pet-battle-dev
    destinations: *dev_allowed_destinations
  - enabled: true
    name: pet-battle-test
    destinations: *test_allowed_destinations
applications:
  pet_battle_api_dev:
    name: pet-battle-api-dev
    enabled: false
    source: https://github.com/petbattle/pet-battle-api.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master
    values:
      fullnameOverride: pet-battle-api
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-api
      image_version: master
      istag:
        enabled: false
      deploymentConfig: false
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-dev
      enabled: true
  pet_battle_api_test:
    name: pet-battle-api-test
    enabled: true
    source: *helm_repo
    chart_name: pet-battle-api
    sync_policy_automated: true
    destination: labs-test
    source_ref: 1.0.6
    values:
      fullnameOverride: pet-battle-api
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-api
      image_version: master
      istag:
        enabled: false
      deploymentConfig: false
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-test
      enabled: true
  pet_battle_dev:
    name: pet-battle-dev
    enabled: false
    source: https://github.com/petbattle/pet-battle.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master
    values:
      app_tag: master
      fullnameOverride: pet-battle
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle
      image_namespace: labs-dev
      config_map: "'http://pet-battle-api-labs-dev.apps.hivec.sandbox1862.opentlc.com'"
    project:
      name: pet-battle-dev
      enabled: true
  pet_battle_test:
    name: pet-battle-test
    enabled: true
    source: *helm_repo
    chart_name: pet-battle
    sync_policy_automated: true
    destination: labs-test
    source_ref: 1.0.3
    values:
      app_tag: master
      fullnameOverride: pet-battle
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle
      image_namespace: labs-test
      image_version: "master"
      config_map: '{ "catsUrl": "http://pet-battle-api-labs-test.apps.hivec.sandbox1459.opentlc.com", "tournamentsUrl": "http://pet-battle-tournament-labs-test.apps.hivec.sandbox1459.opentlc.com", "keycloak": { "issuer": "https://keycloak-labs-test.apps.hivec.sandbox1459.opentlc.com/auth/realms/pbrealm", "redirectUri": "http://pet-battle-labs-test.apps.hivec.sandbox1459.opentlc.com/*", "clientId": "pbclient", "responseType": "code", "scope": "openid profile email", "requireHttps": false, "showDebugInformation": true, "disableAtHashCheck": true } }'
    project:
      name: pet-battle-test
      enabled: true
  pet_battle_tournament_dev:
    name: pet-battle-tournament-dev
    enabled: false
    source: https://github.com/petbattle/tournamentservice-v1.git
    source_path: chart
    sync_policy_automated: true
    destination: labs-dev
    source_ref: master
    values:
      fullnameOverride: pet-battle-tournament
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle-tournament
      image_namespace: labs-dev
      image_version: master
      istag:
        enabled: false
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-dev
      enabled: true
  pet_battle_tournament_test:
    name: pet-battle-tournament-test
    enabled: true
    source: *helm_repo
    chart_name: pet-battle-tournament
    sync_policy_automated: true
    destination: labs-test
    source_ref: 1.0.13
    values:
      fullnameOverride: pet-battle-tournament
      image_repository: image-registry.openshift-image-registry.svc:5000
      image_name: pet-battle
      image_namespace: labs-test
      image_version: "b281740"
      istag:
        enabled: false
      pet-battle-infra:
        app_domain: apps.hivec.sandbox1459.opentlc.com
    ignore_differences: *ignore_differences
    project:
      name: pet-battle-test
      enabled: true
