---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pet-battle-alerts
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: petbattle.rules
    rules:
    - alert: PetBattleApiNotAvailable
      labels:
        namespace: {{ .Release.Namespace }}
      annotations:
        message:  {{ printf "'Pet Battle Api in namespace {{ $labels.namespace }} is not available for the last 1 minutes.'" }}
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="pet-battle-api",namespace="{{ .Release.Namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
    - alert: PetBattleNotAvailable
      labels:
        namespace: {{ .Release.Namespace }}
      annotations:
        message: {{ printf "'Pet Battle in namespace {{ $labels.namespace }} is not available for the last 1 minutes.'" }}
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="pet-battle",namespace="{{ .Release.Namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
    - alert: PetBattleTournamentNotAvailable
      labels:
        namespace: {{ .Release.Namespace }}
      annotations:
        message: {{ printf "'Pet Battle Tournament in namespace {{ $labels.namespace }} is not available for the last 1 minutes.'" }}
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="pet-battle-tournament",namespace="{{ .Release.Namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
