apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: helm-deploy-pipeline
  labels:
    rht-labs.com/uj: pb-ci-cd
spec:
  serviceAccountNames:
    - taskName: helm-upgrade-from-repo
      serviceAccountName: argocd-application-controller
  workspaces:
    - name: shared-workspace
    - name: argocd-env-secret
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_URL
    type: string
    default: ""
  - name: GIT_REVISION
    type: string
    default: "master"
  - name: GIT_REF
    type: string
    default: "refs/heads/master"
  - name: GIT_SHORT_REVISION
    type: string
    default: ""
  - name: GIT_BRANCH
    type: string
    default: "master"
  - name: HELM_CHART_VERSION
    type: string
    default: ""
  - name: HELM_OVERWRITE_VALUES
    type: string
    default: "image_repository=image-registry.openshift-image-registry.svc:5000,image_version=$(params.GIT_SHORT_REVISION),image_namespace=$(params.DEV_NAMESPACE)"
  - name: BUILD_NAMESPACE
    type: string
    default: "labs-ci-cd"
  - name: DEV_NAMESPACE
    type: string
    default: "labs-dev"
  - name: TEST_NAMESPACE
    type: string
    default: "labs-test"
  - name: APP_OF_APPS_DEV_KEY
    type: string
    default: ""
  - name: APP_OF_APPS_TEST_KEY
    type: string
    default: ""
  - name: APP_OF_APPS_TEST_STAGE
    type: string
    default: ""
  tasks:
    - name: fetch-cicd-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "https://github.com/petbattle/pb-ci-cd.git"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/cicd"
        - name: deleteExisting
          value: "true"

    - name: helm-argocd-apps-master # deploy to test + stage
      conditions:
      - conditionRef: is-equal
        params:
          - name: left
            value: "master"
          - name: right
            value: "$(params.GIT_BRANCH)"
      taskRef:
        name: helm-template-from-source
      workspaces:
        - name: source
          workspace: shared-workspace
      params:
        - name: charts_dir
          value: "$(params.APPLICATION_NAME)/cicd/applications/deployment"
        - name: values_file
          value: argo-app-of-apps.yaml
        - name: release_name
          value: my
        - name: target_namespace
          value: "$(params.BUILD_NAMESPACE)"
        - name: overwrite_values
          value: "foo=bar" # these are in git
      runAfter:
        - fetch-cicd-repository

    - name: helm-install-apps-branches # only deploy to dev
      conditions:
      - conditionRef: is-not-equal
        params:
          - name: left
            value: "master"
          - name: right
            value: "$(params.GIT_BRANCH)"
      taskRef:
        name: helm-upgrade-from-repo
      params:
        - name: helm_repo_name
          value: "nexus"
        - name: helm_repo_url
          value: "http://sonatype-nexus-service:8081/repository/helm-charts/"
        - name: chart_name
          value: "$(params.APPLICATION_NAME)"
        - name: release_name
          value: "$(params.GIT_BRANCH)"
        - name: release_version
          value: "$(params.HELM_CHART_VERSION)"
        - name: release_namespace
          value: "$(params.DEV_NAMESPACE)"
        - name: overwrite_values
          value: "$(params.HELM_OVERWRITE_VALUES)"
      runAfter:
        - fetch-cicd-repository

    - name: argocd-sync-application-master
      retries: 3
      taskRef:
        name: argocd-sync-and-wait
      workspaces:
        - name: argocd-env-secret
          workspace: argocd-env-secret
      params:
        - name: application-name
          value: "-l app.kubernetes.io/instance=$(params.APPLICATION_NAME)" # sync by label, multiple apps different namespaces maybe synced
        - name: flags
          value: --insecure
        - name: revision
          value: "$(params.GIT_REVISION)"
      runAfter:
        - helm-argocd-apps-master
