apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-tagging-pipeline
  labels:
    rht-labs.com/uj: pb-ci-cd
spec:
  workspaces:
    - name: shared-workspace
    - name: git-auth-secret
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_REPO_URL
    type: string
    description: Git cicd repo url
    default: "https://github.com/petbattle/pb-ci-cd.git"
  - name: GIT_TAG
    description: The Git Tag (branch,tag,revision) to set for the app
    type: string
    default: "master"
  - name: ARGOCD_CONFIG_REPO_PATH
    description: The App Values file
    type: string
    default: ""
  - name: APP_OF_APPS_KEY
    type: string
    default: ""
  tasks:
    - name: fetch-cicd-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.GIT_REPO_URL)"
        - name: revision
          value: "main"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/cicd"
        - name: deleteExisting
          value: "true"

    - name: git-commit
      retries: 1
      taskRef:
        name: git-commit-argo-versions
      workspaces:
        - name: git-auth-secret
          workspace: git-auth-secret
        - name: output
          workspace: shared-workspace
      params:
      - name: WORK_DIRECTORY
        value: "$(params.APPLICATION_NAME)/cicd"
      - name: GIT_TAG
        value: "$(params.GIT_TAG)"
      - name: APP_OF_APPS_KEY
        value: "$(params.APP_OF_APPS_KEY)"
      - name: ARGOCD_CONFIG_REPO_PATH
        value: "$(params.ARGOCD_CONFIG_REPO_PATH)"
      runAfter:
      - fetch-cicd-repository
