apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: test-chart-upload-pipeline
  labels:
    rht-labs.com/uj: pb-ci-cd
spec:
  workspaces:
    - name: shared-workspace
  params:
  - name: APPLICATION_NAME
    type: string
    default: ""
  - name: GIT_URL
    type: string
    default: ""
  - name: GIT_REF
    type: string
    default: "master"
  tasks:
    - name: fetch-app-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: "$(params.GIT_URL)"
        - name: revision
          value: "$(params.GIT_REF)"
        - name: subdirectory
          value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
        - name: deleteExisting
          value: "true"

    - name: upload-chart
      retries: 1
      taskRef:
        name: helm-upload-chart
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
      - name: WORK_DIRECTORY
        value: "$(params.APPLICATION_NAME)/$(params.GIT_REF)"
      runAfter:
      - fetch-app-repository
