---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pet-battle-alerts
  namespace: {{ .Release.Namespace }}
spec:
  groups:
  - name: petbattle.rules
    rules:
    - alert: PetBattleApiNotAvailable
      annotations:
        message: 'Pet Battle Api in namespace {{ .Release.Namespace }} is not available for the last 1 minutes.'
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="pet-battle-api",namespace="{{ .Release.Namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
    - alert: PetBattleNotAvailable
      annotations:
        message: 'Pet Battle in namespace {{ .Release.Namespace }} is not available for the last 1 minutes.'
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="pet-battle",namespace="{{ .Release.Namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
    - alert: PetBattleTournamentNotAvailable
      annotations:
        message: 'Pet Battle Tournament in namespace {{ .Release.Namespace }} is not available for the last 1 minutes.'
      expr: (1 - absent(kube_pod_status_ready{condition="true",namespace="{{ .Release.Namespace }}"} * on(pod) group_left(label_app_kubernetes_io_component) kube_pod_labels{label_app_kubernetes_io_component="pet-battle-tournament",namespace="{{ .Release.Namespace }}"})) == 0
      for: 1m
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
    - alert: PetBattleApiMaxHttpRequestTime
      annotations:
        message: 'Pet Battle Api max http request time over last 5 min in namespace {{ .Release.Namespace }} exceeds 1.5 sec.'
      expr: max_over_time(http_server_requests_seconds_max{service="pet-battle-api",namespace="{{ .Release.Namespace }}"}[5m]) > 1.5
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
    - alert: PetBattleTournamentMaxHttpRequestTime
      annotations:
        message: 'Pet Battle Tournament max http request time over last 5 min in namespace {{ .Release.Namespace }} exceeds 1.5 sec.'
      expr: max_over_time(http_server_requests_seconds_max{service="pet-battle-tournament",namespace="{{ .Release.Namespace }}"}[5m]) > 1.5
      labels:
        severity: {{ .Values.petbattle.rules.severity }}
