apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: build-images
  labels:
    rht-labs.com/uj: ubiquitous-journey
spec:
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
