apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-source
  labels:
    rht-labs.com/uj: ubiquitous-journey
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
