---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pet-battle-api-deploy
  labels:
    rht-labs.com/uj: pb-ci-cd
objects:
- apiVersion: tekton.dev/v1beta1
  kind: PipelineRun
  metadata:
    generateName: pet-battle-api-deploy-
    annotations:
      argocd.argoproj.io/sync-options: Prune=false
      argocd.argoproj.io/compare-options: IgnoreExtraneous
  spec:
    pipelineRef:
      name: helm-deploy-pipeline
    workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: build-images
    - name: argocd-env-secret
      secret:
        secretName: argocd-token
    params:
    - name: APPLICATION_NAME
      value: "${APPLICATION_NAME}"
    - name: GIT_URL
      value: https://github.com/eformat/pet-battle-api.git
    - name: GIT_REVISION
      value: "${GIT_REVISION}"
    - name: GIT_REF
      value: ""
    - name: GIT_SHORT_REVISION
      value: "${GIT_SHORT_REVISION}"
    - name: GIT_BRANCH
      value: "${GIT_BRANCH}"
    - name: BUILD_NAMESPACE
      value: "labs-ci-cd"
    - name: DEV_NAMESPACE
      value: "labs-dev"
    - name: TEST_NAMESPACE
      value: "labs-test"
    - name: APP_OF_APPS_DEV_KEY
      value: "pet_battle_api_dev"
    - name: APP_OF_APPS_TEST_KEY
      value: "pet_battle_api_test"
#    - name: MAVEN_BUILD_OPTS # disable tests for example
#      value:
#        - -DskipTests
parameters:
- description: Application Name
  displayName: Application Name
  name: APPLICATION_NAME
  required: true
  value: pet-battle-api
- description: Git tag or revision
  displayName: Git tag or revision
  name: GIT_REVISION
  required: true
  value: master
- description: Git short revision
  displayName: Git short revision
  name: GIT_SHORT_REVISION
  required: true
  value: master
- description: Git branch name
  displayName: Git branch name
  name: GIT_BRANCH
  required: true
  value: master