---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: pet-battle-api-create-webhook
objects:
- apiVersion: tekton.dev/v1beta1
  kind: TaskRun
  metadata:
    generateName: pet-battle-api-create-webhook-
  spec:
    taskRef:
      kind: Task
      name: create-webhook
    podTemplate:
        securityContext:
        runAsNonRoot: true
        runAsUser: 1001
    params:
    - name: GitHubOrg
      value: "eformat"
    - name: GitHubUser
      value: "tekton"
    - name: GitHubRepo
      value: "pet-battle-api"
    - name: GitHubAccessTokenKey
      value: password
    - name: GitHubSecretStringKey
      value: webhook
    - name: ExternalDomain
      value: http://webhook-labs-ci-cd.apps.hivec.sandbox1438.opentlc.com
    timeout: 1h0m0s
    serviceAccountName: pipeline
    workspaces:
    - name: git-auth-secret
      secret:
        secretName: git-auth
