destination: &ci_cd_ns labs-ci-cd

##############
# 🐙 Argo Sync Policy
#############
sync_policy_true: &sync_policy_true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true

sync_policy_no_selfheal: &sync_policy_no_selfheal
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - Validate=true

##############
# 🛎 Argo App of Apps declaration
#############
# enabled true on an app is to tell helm to create an argo app cr for this item
# Custom values override the default values in Helm Charts
applications:
  # Nexus
  - name: nexus
    enabled: true
    source: https://redhat-cop.github.io/helm-charts
    chart_name: sonatype-nexus
    source_path: ""
    source_ref: "0.0.12"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    ignore_differences:
      - group: route.openshift.io
        kind: Route
        jsonPointers:
          - /status/ingress
  # Jenkins
  - name: jenkins
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/jenkins
    source_ref: "jenkins-0.0.23"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    values:
      persistence: false
      source_secrets:
        - name: nexus-password
          username: admin
          password: admin123
      buildconfigs:
      # Jenkins S2I from Red Hat Labs
      - name: *name
        build_trigger_secret: 'shhhhh-this-is-my-super-duper-secret123-shhhhh'
        strategy_type: "Source"
        source_secret: 'git-auth'
        pull_secret: ''
        source_repo: https://github.com/rht-labs/s2i-config-jenkins.git
        source_repo_ref: v1.9
        source_context_dir: '/'
        builder_image_kind: "DockerImage"
        builder_image_name: quay.io/openshift/origin-jenkins
        builder_image_tag: "latest"
      # Jenkins agents for running builds etc
      - name: "jenkins-agent-ansible"
        source_context_dir: "jenkins-agents/jenkins-agent-ansible"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-arachni"
        source_context_dir: "jenkins-agents/jenkins-agent-arachni"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-argocd"
        source_context_dir: "jenkins-agents/jenkins-agent-argocd"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-conftest"
        source_context_dir: "jenkins-agents/jenkins-agent-conftest"
        source_repo: *jarepo
        source_repo_ref: "master"
        builder_image_name: "quay.io/redhat-cop/jenkins-agent-python"
        builder_image_tag: "v1.0"
      - name: "jenkins-agent-erlang"
        source_context_dir: "jenkins-agents/jenkins-agent-erlang"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-golang"
        source_context_dir: "jenkins-agents/jenkins-agent-golang"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-graalvm"
        source_context_dir: "jenkins-agents/jenkins-agent-graalvm"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-gradle"
        source_context_dir: "jenkins-agents/jenkins-agent-gradle"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-helm"
        source_context_dir: "jenkins-agents/jenkins-agent-helm"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-image-mgmt"
        source_context_dir: "jenkins-agents/jenkins-agent-image-mgmt"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-mongodb"
        source_context_dir: "jenkins-agents/jenkins-agent-mongodb"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-mvn"
        source_context_dir: "jenkins-agents/jenkins-agent-mvn"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-npm"
        source_context_dir: "jenkins-agents/jenkins-agent-npm"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-python"
        source_context_dir: "jenkins-agents/jenkins-agent-python"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-ruby"
        source_context_dir: "jenkins-agents/jenkins-agent-ruby"
        source_repo: *jarepo
        source_repo_ref: "master"
      - name: "jenkins-agent-rust"
        source_context_dir: "jenkins-agents/jenkins-agent-rust"
        source_repo: *jarepo
        source_repo_ref: "master"
    ignore_differences:
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
          - /spec/template/spec/containers/0/image
          - /spec/triggers/0/imageChangeParams/lastTriggeredImage
      - group: build.openshift.io
        kind: BuildConfig
        jsonPointers:
          - /spec/triggers
  # Pact-broker
  - name: pact-broker
    enabled: false
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: charts/pact-broker
    source_ref: "pact-broker-0.0.5"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    values:
      secrets:
        name: pact-broker-secrets
        keys:
          pactBrokerDatabaseUsername: pact_broker_database_username
          pactBrokerDatabasePassword: pact_broker_database_password
          pactBrokerAdmin: pact_broker_admin
          pactBrokerAdminPassword: pact_broker_admin_password
          pactBrokerBasicAuthUsername: pact_broker_user
          pactBrokerBasicAuthPassword: pact_broker_user_password
        values:
          pactBrokerDatabaseUsername: pact_broker_user
          pactBrokerDatabasePassword: thisisdefinitelynotmypassword
          pactBrokerAdmin: admin
          pactBrokerAdminPassword: thisisdefinitelynotmypassword
          pactBrokerBasicAuthUsername: dev
          pactBrokerBasicAuthPassword: thisisdefinitelynotmypassword
  # Sonarqube
  - name: sonarqube
    enabled: true
    source: https://github.com/redhat-cop/helm-charts.git
    source_path: "charts/sonarqube"
    source_ref: "sonarqube-0.0.12"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    values:
      initContainers: true
      plugins:
        install:
          - https://github.com/checkstyle/sonar-checkstyle/releases/download/8.35/checkstyle-sonar-plugin-8.38.jar
          - https://repo1.maven.org/maven2/org/sonarsource/java/sonar-java-plugin/6.9.0.23563/sonar-java-plugin-6.9.0.23563.jar
          - https://repo1.maven.org/maven2/org/sonarsource/jacoco/sonar-jacoco-plugin/1.1.0.898/sonar-jacoco-plugin-1.1.0.898.jar
          - https://github.com/dependency-check/dependency-check-sonar-plugin/releases/download/2.0.7/sonar-dependency-check-plugin-2.0.7.jar
          - https://github.com/SonarSource/SonarJS/releases/download/6.2.2.13315/sonar-javascript-plugin-6.2.2.13315.jar
          - https://github.com/SonarSource/SonarTS/releases/download/2.1.0.4359/sonar-typescript-plugin-2.1.0.4362.jar
  # Sonarqube setup
  - name: sonarqube-setup
    enabled: true
    source: https://github.com/eformat/sonarqube-jobs
    source_path: charts/quality-gate
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    source_ref: main
    values:
      qualityGate:
        new_coverage:
          enabled: false
  # CodeReady Workspaces
  - name: crw
    enabled: false
    destination: crw
    source: https://github.com/rht-labs/refactored-adventure
    source_path: crw/base
    source_ref: master
    sync_policy: *sync_policy_no_selfheal
    no_helm: true
    ignore_differences:
      - group: org.eclipse.che
        kind: CheCluster
        jsonPointers:
          - /spec
  # Zalenium
  - name: zalenium
    enabled: false
    source: https://github.com/zalando/zalenium.git
    source_path: charts/zalenium
    source_ref: "master"
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    values:
      hub:
        serviceType: ClusterIP
        openshift:
          deploymentConfig:
            enabled: true
          route:
            enabled: true
        persistence:
          enabled: false
        serviceAccount:
          create: false
        desiredContainers: 0
        podAnnotations:
          app: zalenium
  # Hoverfly
  - name: hoverfly
    enabled: false
    source: https://github.com/helm/charts.git
    source_path: incubator/hoverfly
    sync_policy: *sync_policy_true
    destination: *ci_cd_ns
    source_ref: "master"
    values:
      replicaCount: "1"
      openshift:
        route:
          admin:
            enabled: true
            hostname: ""
          proxy:
            enabled: true
            hostname: ""
    ignore_differences:
      - group: route.openshift.io
        kind: Route
        jsonPointers:
          - /status/ingress
          - /spec/host
      - group: apps/v1
        kind: Deployment
        jsonPointers:
          - /spec/replicas
  # Container Security
  - name: container-security-operator
    enabled: true
    destination: openshift-operators
    source: https://github.com/rht-labs/refactored-adventure
    source_path: container-security-operator/base
    source_ref: master
    sync_policy: *sync_policy_true
    no_helm: true
  # Tekton
  - name: tekton
    enabled: true
    destination: openshift-operators
    source: https://github.com/rht-labs/refactored-adventure
    source_path: tekton/base
    source_ref: master
    sync_policy: *sync_policy_true
    no_helm: true
  # CertUtils
  - name: cert-utils
    enabled: true
    destination: openshift-operators
    source: https://github.com/rht-labs/refactored-adventure
    source_path: cert-utils/base
    source_ref: master
    sync_policy: *sync_policy_true
    no_helm: true
  # Knative
  - name: knative
    enabled: true
    destination: openshift-serverless
    source: https://github.com/rht-labs/refactored-adventure
    source_path: knative/serving
    source_ref: master
    sync_policy: *sync_policy_true
    no_helm: true
  # Bootstrap Journey
  - name: bootstrap-journey
    enabled: true
    source: https://github.com/petbattle/ubiquitous-journey.git
    source_path: ubiquitous-journey/bootstrap
    destination: labs-bootstrap
    source_ref: "main"
    sync_policy: *sync_policy_true
    values:
      argocd-operator:
        ignoreHelmHooks: true
    helm_values:
      - values-bootstrap.yaml
  # Pet Battle Ubiquitous Journey
  - name: pet-battle-ubiquitous-journey
    destination: labs-ci-cd
    enabled: true
    source: https://github.com/petbattle/ubiquitous-journey.git
    source_path: tekton
    source_ref: main
    sync_policy: *sync_policy_true
    no_helm: true
