apiVersion: v1
data:
  password: password
  username: username
kind: Secret
metadata:
  labels:
    credential.sync.jenkins.openshift.io: "true"
  name: argocd-token
  namespace: labs-ci-cd
type: kubernetes.io/basic-auth
